version: "3.6"

services:
  db:
    container_name: database
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - django_data:/var/lib/postgresql/data
    networks:
      database_network:

  api:
    container_name: application
    command: python manage.py runserver 0.0.0.0:8000
    user: django
    working_dir: /home/django/src
    depends_on:
      - db
    build:
      context: ../
      target: application
      dockerfile: .docker/Dockerfile
    environment:
      DEBUG: "true"
      DB_HOST: "db"
    ports:
      - "0.0.0.0:8500:8000"
    volumes:
      - ../src/:/home/django/src
    networks:
      database_network:

networks:
  database_network:
    driver: bridge

volumes:
  django_data:
